---
- name:  Create a new user
  hosts: all
  become: true
  vars:
    user_password: "{{ 'mypassword' | password_hash('sha512') }}"
  tasks:
    name: Create a user with hashed password
    user:
      name: devops_user
      password: "{{ user_password  }}"
      state: present
